//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTask
    {
        public int ta_TareaPk { get; set; }
        public string ta_Nombre { get; set; }
        public bool te_Estado { get; set; }
        public Nullable<System.DateTime> te_FechaCreacion { get; set; }
        public string te_Descripcion { get; set; }
        public Nullable<System.DateTime> te_FechaVencimiento { get; set; }
        public int te_UsuarioFk { get; set; }
    
        public virtual tblUsers tblUsers { get; set; }
    }
}
