//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsTask.test
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUsers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUsers()
        {
            this.tblTask = new HashSet<tblTask>();
        }
    
        public int us_Users_Pk { get; set; }
        public string us_UserName { get; set; }
        public string us_Name { get; set; }
        public string us_LastName { get; set; }
        public int us_Age { get; set; }
        public bool us_Estado { get; set; }
        public string us_Password { get; set; }
        public Nullable<bool> us_CreateTask { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTask> tblTask { get; set; }
    }
}
